# Generated by Django 4.1 on 2022-08-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
