# Generated by Django 4.1 on 2022-08-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='compelte',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transction_id',
        ),
    ]
